services:
  app:
    build: .
    ports:
      - 3398:3398
    depends_on:
      - db
    networks:
      - jwt_user

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: senha123rte
      MYSQL_DATABASE: jwt_user
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jwt_user

volumes:
  mysql_data:

networks:
  jwt_user: